// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exfeuvmgmnapjslocxwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZmV1dm1nbW5hcGpzbG9jeHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzc4NjEsImV4cCI6MjA2MjcxMzg2MX0.ZzE7895OQHX4pkmDu8myDja47YGoQ5jdIRVSFiOx_qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);